apiVersion: v1
kind: Secret
metadata:
  name: calendar-app-secrets
  namespace: calendar-app
type: Opaque
stringData:
  VITE_CLIENT_ID: 27c750cd-8d7b-45b1-9dec-c52e444eefc9
  VITE_TENANT_ID: b41b72d0-4e9f-4c26-8a69-f949f367c91d
  VITE_REDIRECT_URI: http://localhost:8080/
  VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4anVmenVnZWd4bWVheWdleHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDk0NjQsImV4cCI6MjA1Nzk4NTQ2NH0.OiYJ6cpu7CFScpKEtQ5ktesZ4pLNzSdO-ggfriX9pKk
  VITE_SUPABASE_URL: https://zxjufzugegxmeaygexzx.supabase.co
